name: azure-forecasting
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pip=24.2
  - python=3.10.14
  - ipykernel=6.29.5
  - jupyterlab=4.2.4
  - matplotlib=3.9.1
  - mlforecast=0.13.3
  - neuralforecast=1.7.4
  - numpy=1.23.5
  - pandas=2.2.2
  - plotly=5.23.0
  - pytorch=2.4.0
  - pytorch-cuda=11.8
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - seaborn=0.13.2
  - sktime=0.31.0
  - statsforecast=1.7.6
  - statsmodels=0.14.2
  - hierarchicalforecast=0.4.1
  - ipywidgets=8.1.3
  - pip:
      - azure-ai-ml==1.18.0
      - azure-common==1.1.28
      - azure-core==1.30.2
      - azure-identity==1.17.1
      - azure-mgmt-core==1.4.0
      - azure-storage-blob==12.22.0
      - azure-storage-file-datalake==12.16.0
      - azure-storage-file-share==12.17.0
      - isodate==0.6.1
      - marshmallow==3.21.3
      - msal==1.30.0
      - msal-extensions==1.2.0
      - msrest==0.7.1
      - oauthlib==3.2.2
      - opencensus==0.11.4
      - opencensus-ext-azure==1.1.13
      - opencensus-ext-logging==0.1.1
      - polars==1.2.1
      - portalocker==2.10.1
      - pydash==8.0.3
      - pyjwt==2.9.0
      - requests-oauthlib==2.0.0
      - strictyaml==1.7.3
