name: forecast-env
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.14
  - pip
  - pytorch=2.4.0
  - pytorch-cuda=11.8
  - pip:
    - azure-ai-ml
    - azure-identity
    - azure-cli
    - azureml-fsspec
    - azureml-mlflow
    - mlflow
    - mldesigner
    - mltable
    - dask[complete]
    - dask_mpi
    - ray[data,train,tune,serve]
    - ipykernel
    - jupyterlab
    - numpy
    - scipy
    - cupy-cuda11x
    - pandas
    - polars
    - matplotlib
    - seaborn
    - plotly
    - ipywidgets
    - scikit-learn
    - lightgbm
    - statsmodels
    - sktime
    - statsforecast
    - mlforecast
    - hierarchicalforecast
    