$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_test_split
display_name: Train test split
version: 1
type: command

inputs:
  timeseries: 
    type: uri_folder
  freq:
    type: string
  lags:
    type: string
outputs:
  train_data:
    type: uri_folder
  test_data:
    type: uri_file

code: ../../
environment: azureml:forecast-env@latest

command: >-
  python -m src.azure.train_test_split
  --input ${{inputs.timeseries}}
  --output-train ${{outputs.train_data}}
  --output-test ${{outputs.test_data}}
  --freq ${{inputs.freq}}
  --lags ${{inputs.lags}}
